name: eslintm
on: 
  pull_request:
    branches: 
      - master
      - dev
      - devtest
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          reporter: github-check # Change reporter.

